tags:
- name: targets
  description: targets API

# [POST] targets/radar
  post:
    tags:
    - targets
    summary: Get next target coordinates
    parameters:
    - name: body
      in: body
      description: targets Data
      required: true
      schema:
        $ref: '#/definitions/targets'
    responses:
      200:
        description: 'OK'
      400:
        description: 'Bad Request'
      500:
        description: 'Server Error'

# definitions
definitions:
  targets:
    type: object
    required:
        - protocols
        - scan
    properties:
      protocols:
        type: array
        items:
          type: string
        description: possible protocols to get next target
      scan:
        type: array
        items: 
          type: object
        description: targets array data


schemes:
 - https
 - http
